repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.1.1 # <-- stable version
    hooks:
      - id: black
        args: [] # don't override line length, pyproject.toml will be used
