"""Curated IANA timezone choices for the application timezone picker.

This hand-maintained list should be appended when IANA adds a widely used zone.
The guard tests cross-check membership against zoneinfo.available_timezones.
The save endpoint accepts any ZoneInfo-resolvable key, so absence from this
curated picker never blocks a valid stored value.
"""

CURATED_TIMEZONES: dict[str, list[str]] = {
    "UTC": ["UTC"],
    "Africa": [
        "Africa/Abidjan",
        "Africa/Accra",
        "Africa/Addis_Ababa",
        "Africa/Algiers",
        "Africa/Cairo",
        "Africa/Casablanca",
        "Africa/Dakar",
        "Africa/Dar_es_Salaam",
        "Africa/Johannesburg",
        "Africa/Lagos",
        "Africa/Nairobi",
        "Africa/Tunis",
    ],
    "America": [
        "America/Anchorage",
        "America/Argentina/Buenos_Aires",
        "America/Bogota",
        "America/Caracas",
        "America/Chicago",
        "America/Costa_Rica",
        "America/Denver",
        "America/Detroit",
        "America/Edmonton",
        "America/Guatemala",
        "America/Guayaquil",
        "America/Halifax",
        "America/Havana",
        "America/Lima",
        "America/Los_Angeles",
        "America/Manaus",
        "America/Mexico_City",
        "America/Montevideo",
        "America/New_York",
        "America/Panama",
        "America/Phoenix",
        "America/Puerto_Rico",
        "America/Santiago",
        "America/Sao_Paulo",
        "America/St_Johns",
        "America/Toronto",
        "America/Vancouver",
        "America/Winnipeg",
    ],
    "Asia": [
        "Asia/Almaty",
        "Asia/Amman",
        "Asia/Baghdad",
        "Asia/Bangkok",
        "Asia/Beirut",
        "Asia/Colombo",
        "Asia/Dhaka",
        "Asia/Dubai",
        "Asia/Ho_Chi_Minh",
        "Asia/Hong_Kong",
        "Asia/Jakarta",
        "Asia/Jerusalem",
        "Asia/Kabul",
        "Asia/Karachi",
        "Asia/Kathmandu",
        "Asia/Kuala_Lumpur",
        "Asia/Kuwait",
        "Asia/Manila",
        "Asia/Muscat",
        "Asia/Nicosia",
        "Asia/Novosibirsk",
        "Asia/Phnom_Penh",
        "Asia/Qatar",
        "Asia/Riyadh",
        "Asia/Seoul",
        "Asia/Shanghai",
        "Asia/Singapore",
        "Asia/Taipei",
        "Asia/Tashkent",
        "Asia/Tehran",
        "Asia/Tokyo",
        "Asia/Ulaanbaatar",
        "Asia/Yerevan",
    ],
    "Atlantic": [
        "Atlantic/Azores",
        "Atlantic/Bermuda",
        "Atlantic/Canary",
        "Atlantic/Cape_Verde",
        "Atlantic/Reykjavik",
        "Atlantic/South_Georgia",
        "Atlantic/Stanley",
    ],
    "Australia": [
        "Australia/Adelaide",
        "Australia/Brisbane",
        "Australia/Darwin",
        "Australia/Hobart",
        "Australia/Melbourne",
        "Australia/Perth",
        "Australia/Sydney",
    ],
    "Europe": [
        "Europe/Amsterdam",
        "Europe/Andorra",
        "Europe/Athens",
        "Europe/Belgrade",
        "Europe/Berlin",
        "Europe/Brussels",
        "Europe/Bucharest",
        "Europe/Budapest",
        "Europe/Chisinau",
        "Europe/Copenhagen",
        "Europe/Dublin",
        "Europe/Gibraltar",
        "Europe/Helsinki",
        "Europe/Istanbul",
        "Europe/Kyiv",
        "Europe/Lisbon",
        "Europe/London",
        "Europe/Luxembourg",
        "Europe/Madrid",
        "Europe/Malta",
        "Europe/Minsk",
        "Europe/Monaco",
        "Europe/Moscow",
        "Europe/Oslo",
        "Europe/Paris",
        "Europe/Prague",
        "Europe/Riga",
        "Europe/Rome",
        "Europe/Sofia",
        "Europe/Stockholm",
        "Europe/Tallinn",
        "Europe/Vienna",
        "Europe/Vilnius",
        "Europe/Warsaw",
        "Europe/Zurich",
    ],
    "Pacific": [
        "Pacific/Auckland",
        "Pacific/Chatham",
        "Pacific/Fiji",
        "Pacific/Guam",
        "Pacific/Honolulu",
        "Pacific/Noumea",
        "Pacific/Pago_Pago",
        "Pacific/Port_Moresby",
        "Pacific/Tahiti",
        "Pacific/Tongatapu",
    ],
}


def curated_zone_keys() -> set[str]:
    """Return the flattened set of curated timezone keys."""
    return {zone for zones in CURATED_TIMEZONES.values() for zone in zones}
