name: Build Dev Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image (no push yet)
        run: |
          docker build -t listarr:dev .